server:
  port: 2050
spring:
  application:
    name: turbine
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://xgf:123456@localhost:2030/eureka/
turbine:
  app-config: service-order
  cluster-name-expression: "'http://192.168.1.1:2021/hystrix.stream'"
