server:
  port: 2080
spring:
  application:
    name: ms-gateway-zuul
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://xgf:123456@localhost:8761/eureka/
zuul:
  routes:
    service-user: /user/**
    service-order: /order/**
