server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://xgf:123456@localhost:8761/eureka/
spring:
  application:
    name: eureka-server
  security:
    user:
      name: xgf
      password: 123456
